loan4u/urls.py
from django.contrib import admin
from django.urls import path
from loan_app import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('logout/',views.user_logout,name='logout'),
    path('home/',views.home,name='home'),
    path('loan_app/',include('loan_app.urls')),
]

loan_app/urls.py
from django.conf.urls import url
from loan_app import views
from django.urls import path

app_name = 'loan_app'

urlpatterns =[
    path('login/',views.user_login,name='user_login'),
    path('signup/',views.signup,name='signup'),
    #path('reg_success/',views.)

]

loan_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class LoanInfo(models.Model):
    loanno = models.CharField(max_length=6,unique=True)
    loantype = models.CharField(max_length=20)
    loanprovider = models.CharField(max_length=30)
    loanamt = models.DecimalField(max_digits=10,decimal_places=2)
    loanduration = models.DurationField()
    loanintr = models.DecimalField(max_digits=4,decimal_places=2)
    loanee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='loanee',null=True)

    def __str__(self):
        return self.loanno+",Type =  "+self.loantype

class UserLoanInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.PROTECT)

    address = models.CharField(max_length=264)
    #loan1 = models.ForeignKey(LoanInfo,blank=True,on_delete=models.PROTECT)
    #loan2 = models.ForeignKey(LoanInfo,blank=True,on_delete=models.PROTECT)
    #loan3 = models.ForeignKey(LoanInfo,blank=True,on_delete=models.PROTECT)

    def __str__(self):
        return self.user.username

loan_app/forms.py
from django import forms
from django.contrib.auth.models import User
from loan_app.models import UserLoanInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name','last_name','email','username','password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class UserLoanInfoForm(forms.ModelForm):
    class Meta():
        model = UserLoanInfo
        fields = ('address',)  #add loan1,loan2,loan3

loan_app/views.py
from django.shortcuts import render
from loan_app.forms import UserForm, UserLoanInfoForm
from loan_app.models import LoanInfo
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request,'loan_app/index.html')

def home(request):
    if request.method == 'POST' :
        loanamtinput = request.POST.get('loanamtinput',None)
        loaninstallment = request.POST.get('loaninstallment',None)
        loantype = request.POST.get('loanlist',None)
        print(loanamtinput)
        print(loaninstallment)
        print(loantype)
        return HttpResponse("Loan edukand pani eduth paisa undaku malaree")
    else:
        loanlist = LoanInfo.objects.values_list('loantype',flat=True).distinct()
        #print(loanlist)
        return render(request,'loan_app/home.html',{'loanlist':loanlist})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Account Not Active")
        else:
            return HttpResponse("Invalid Login Credentials")
    else:
        return render(request,'loan_app/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def signup(request):
    registered = False
    if(request.method == "POST"):
        user_form = UserForm(data=request.POST)
        loaninfo_form = UserLoanInfoForm(data=request.POST)

        if(user_form.is_valid() and loaninfo_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            loaninfo = loaninfo_form.save(commit=False)
            loaninfo.user = user
            loaninfo.save()

            registered = True
            return  render(request,'loan_app/reg_success.html')
            

        else:
            print(user_form.errors)
            messages.info(request,user_form.errors)
            return render(request,'loan_app/signup.html',
                                    {'user_form':user_form,
                                    'loaninfo_form':loaninfo_form,
                                    'registered':registered})
            #print(user_form.errors,loaninfo_form.errors)

    else:
        user_form = UserForm()
        loaninfo_form = UserLoanInfoForm()

    return render(request,'loan_app/signup.html',
                            {'user_form':user_form,
                              'loaninfo_form':loaninfo_form,
                              'registered':registered})

templates/loan_app/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>loan4u</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <style>
      h1{text-align:right;;}
    </style>
  </head>
  <body>
    <div class ="container">
      <div class="jumbotron">
        <h1>
          {% if user.is_authenticated %}
            <br><h1>Welcome {{ user.username }}
            <a href="{% url 'logout' %}"><font size="3" color="black">Logout</a>
        </h1>
      </div>
    </div>
            <form  method="POST">
              {% csrf_token %}
              <select name="loanlist">
                {% for element in loanlist %}
                  <option value={{ element }}>{{ element }}</option>
                {% endfor %}
              </select>
              <input type="number" name="loanamtinput" placeholder="Enter the Loan : ">
              <input type="number" name="loaninstallment" value="Enter your monthly installments : ">
              <button type="submit" >Search</button>
            </form>
          {% else %}
            <li><a href="{% url 'loan_app:user_login' %}">Click here to Login</a></li>
          {% endif %}
    </h1>
  </body>
</html>

templates/loan_app/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>loan4u</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <link rel="stylesheet" href="{% static "loan_app/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/materialize.min.css" %}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/tooplate.css" %}"/>

</head>

<body id="home">
    <div class="container tm-home-mt tm-home-container">
        <div class="row">
            <div class="col-12">
                <div class="tm-home-left">
                    <h1 class="tm-site-title">LOAN FOR YOU</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <div class="tm-home-left mt-3 font-weight-light">
                    <p class="black-text tm-mb-35">Welcome to your everyday loan portal! Our team thrives to gives you the best possible loan offer adhered to your needs!!</p>
                    <p class="black-text tm-mb-35">Just sign up, login, enter your requirements and get the best loan offer that is most suited for your needs. As simple as that </p>
                </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <ul class="list-group tm-home-list tm-bg-black font-weight-light">
                    <li class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'loan_app:signup' %}" class="tm-white-text">01. Sign Up</a>
                    </li>
                    <li class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'loan_app:user_login' %}" class="tm-white-text">02. Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <footer class="row tm-mt-big mb-3">
        <div class="col-xl-12 text-center font-weight-light">
            <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                Copyright &copy; 2018 Loan4U
            </p>
        </div>
    </footer>
</body>

</html>

templates/loan_app/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>loan4u</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <link rel="stylesheet" href="{% static "loan_app/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/materialize.min.css"%}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/tooplate.css"%}"/>
</head>

<body id="login">
    <div class="container">
        <div class="row tm-register-row tm-mb-35">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 tm-login-l">
                <form action="" method="post" class="tm-bg-black p-5 h-100">
                    {% csrf_token %}
                    <div class="input-field">
                        <input placeholder="Username" id="username" name="username" type="text" class="validate">
                    </div>
                    <div class="input-field mb-5">
                        <input placeholder="Password" id="password" name="password" type="password" class="validate">
                    </div>
                    <div class="tm-flex-lr">
                        <a href="#" class="white-text small">Forgot Password?</a>
                        <button type="submit" class="waves-effect btn-large btn-large-white px-4 black-text rounded-0">Login</button>
                    </div>
                </form>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 tm-login-r">
                <header class="font-weight-light tm-bg-black p-5 h-100">
                    <h3 class="mt-0 text-white font-weight-light">Your Login</h3>
                </header>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 ml-auto mr-0 text-center">
                <a href="{% url 'loan_app:signup' %}" class="waves-effect btn-large btn-large-white px-4 black-text rounded-0">Create New Account</a>
            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                    Copyright &copy; 2018 Loan4U
                </p>
            </div>
        </footer>
    </div>

    <script src="{% static "loan_app/js/jquery-3.2.1.slim.min.js" %}"></script>
    <script src="{% static "loan_app/js/materialize.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>

templates/loan_app/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" typh="image/ico" ref="images/favicon.ico" />
    <title>loan4u</title>
  </head>
  <body>

  </body>
</html>

templates/loan_app/reg_success.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>loan4U</title>
  </head>
  <body>
    <h1>Registration Successful</h1>
    <p>You have been succesfully registered.Click here to <a href="{% url 'loan_app:user_login' %}">Login</a></p>

  </body>
</html>

templates/loan_app/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>loan4u</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <link rel="stylesheet" href="{% static "loan_app/css/bootstrap.min.css"%}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/materialize.min.css"%}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/tooplate.css"%}"/>
</head>

<body id="register">
    <div class="container">
        <div class="row tm-register-row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 tm-register-col-l">
                <form action="" method="post">
                    <div class="mb-2">
                        <label class="mr-4">
                            <input class="with-gap" name="title" type="radio" value="mr" />
                            <span>Mr.</span>
                        </label>
                        <label class="mr-4">
                            <input class="with-gap" name="title" type="radio" value="ms" />
                            <span>Ms.</span>
                        </label>
                        <label>
                            <input class="with-gap" name="title" type="radio" value="mrs" />
                            <span>Mrs.</span>
                        </label>
                    </div>

                    <div class="input-field">
                        <input placeholder="First Name" id="first_name" name="first_name" type="text" class="validate">
                    </div>
                    <div class="input-field">
                        <input placeholder="Last Name" id="last_name" name="last_name" type="text" class="validate">
                    </div>
                    <div class="input-field">
                        <input placeholder="Email" id="email" name="email" type="text" class="validate">
                    </div>
                    <div class="input-field">
                        <input placeholder="Mobile" id="mobile" name="mobile" type="text" class="validate">
                    </div>
                    <div class="input-field">
                        <input placeholder="Address" id="address" name="address" type="text" class="validate">
                    </div>
                    <div class="input-field">
                        <input placeholder="District/Province" id="district" name="district" type="text" class="validate">
                    </div>
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 pl-0 tm-pr-xs-0">
                            <select name="city">
                                <option value="-">Your City</option>
                                <option value="Bangkok">Bangkok</option>
                                <option value="Yangon">Yangon</option>
                                <option value="Mumbai">Mumbai</option>
                                <option value="Singapore">Singapore</option>
                            </select>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 pr-0 tm-pl-xs-0">
                            <div class="input-field">
                                <input placeholder="Zip Code" id="zipcode" name="zipcode" type="text" class="validate">
                            </div>
                        </div>
                    </div>
                    <div class="text-right mt-4">
                        <button type="submit" class="waves-effect btn-large btn-large-white px-4 black-text">SUBMIT</button>
                    </div>
                </form>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 tm-register-col-r">
                <header class="mb-5">
                    <h3 class="mt-0 text-white">REGISTER Yourself</h3>
                    <p class="grey-text">DESCRIPTION GOES HERE</p>
                </header>

            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12">
                <p class="text-center grey-text text-lighten-2 tm-footer-text-small">
                    Copyright &copy; 2018 Loan4U
                </p>
            </div>
        </footer>
    </div>

    <script src="{% static "loan_app/js/jquery-3.2.1.slim.min.js" %}"></script>
    <script src="{% static "loan_app/js/materialize.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>

templates/loan_app/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>loan4U</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <link rel="stylesheet" href="{% static "loan_app/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/materialize.min.css" %}"/>
    <link rel="stylesheet" href="{% static "loan_app/css/tooplate.css" %}"/>
</head>

<body id="register">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <header class="mb-5">
                    <h3 class="mt-0 white-text">Sign-up Form</h3>
                    <p class="grey-text mb-4">Fill in the necessary details to join the loan4u family!</p>
                    <p class="grey-text mb-4">Hurry!! You are just minutes away from getting to know your best loan offer</p>
                </header>
            </div>
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: #FF0000">Error {{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <form class="tm-signup-form" method="POST">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ loaninfo_form.as_p }}

                    <div class="text-right mt-4">
                        <button type="submit" class="waves-effect btn-large btn-large-white px-4 tm-border-radius-0">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12">
                <p class="text-center grey-text text-lighten-2 tm-footer-text-small">
                    Copyright &copy; 2018 Loan4U
                </p>
            </div>
        </footer>
    </div>

    <script src="{% static "loan_app/js/jquery-3.2.1.slim.min.js" %}"></script>
    <script src="{% static "loan_app/js/materialize.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>